#!/bin/bash
set -e

SCRIPT_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_HOME/../../dev.env fast

pushd $APP_ROOT/client > /dev/null

MAIN_JS=$(find src -type f -name '*.js' -not -name test.js | xargs ls -1t)
echo $MAIN_JS | tr " " "\n"  | parallel --halt 2 "lint-single-js .main.jshintrc {}"

TEST_JS=$(find src -type f -name test.js | xargs ls -1t)
echo $TEST_JS | tr " " "\n"  | parallel --halt 2 "lint-single-js .test.jshintrc {}"
